sonar.projectKey=securebank
sonar.projectName=SecureBank DevSecOps
sonar.projectVersion=1.0.0

# Source directories
sonar.sources=backend/src,frontend/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.spec.ts,**/coverage/**

# TypeScript
sonar.typescript.tsconfigPath=backend/tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
