sonar.projectKey=Son0fGuilliman_Secure-Bank
sonar.organization=son0fguilliman
sonar.projectName=SecureBank DevSecOps

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.spec.ts,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8